### ISSUE TITLE
Getting Call to undefined method MeSomb\Signature::nonceGenerator() on $payment->makeCollect()

### ISSUE THREAD

**Issue by ExcelDurant** [hachther/mesomb-php-client#1]
It looks like the MeSomb\Signature class in the hachther/mesomb-php Laravel package doesn't have a `nonceGenerator()` method, hence the error message you're seeing. 

This is after installing the package in a newly created laravel project
PHP version: PHP 8.1.7
Laravel version: 8.75

**Comment by hachther** [comment]
Yes. This method is no more exists and the README file has been updated.
